# Generated by Django 5.1.1 on 2024-09-11 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='pertence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.funcionario'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='descricao',
            field=models.CharField(help_text='Descrição do Documento', max_length=100),
        ),
    ]
